os.loadAPI('display/displayHandler.lua')
monitor = peripheral.wrap('back')
monitor.clear()
monitor.setBackgroundColor(colors.black)
Button1 = displayHandler.Button.new(colors.black, colors.white, 1, 2, 3, 4, 'Test')
print('This file is used to test the module displayHandler!')